name: Update Data

on:
  #schedule:
    #- cron: '0 1 * * *'  # 毎日朝5時に実行
  workflow_dispatch:  # 手動実行のトリガー

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # リポジトリをチェックアウト

    - name: Set up Python
      uses: actions/setup-python@v4  # Pythonをセットアップ
      with:
        python-version: '3.11'  # Python 3.11を使用

    - name: Upgrade pip
      run: python -m pip install --upgrade pip  # pipをアップグレード

    - name: Install dependencies
      run: pip install requests yt-dlp

    - name: Setup Tor
      uses: tor-actions/setup-tor@main
      with:
        tor-version: '0.4.5.7'

    - name: Setup additional Tor instances
      run: |
        for i in $(seq 1 9); do
          sudo cp /etc/tor/torrc /etc/tor/torrc$i
          sudo sed -i "s/SocksPort 9050/SocksPort 905$i/" /etc/tor/torrc$i
          sudo tor -f /etc/tor/torrc$i &
        done

    - name: Update data
      run: python update.py

    - name: Commit and push if changes
      if: github.ref == 'refs/heads/main'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "${GITHUB_ACTOR}"
        git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
        if [ "$(git diff --shortstat)" != "" ]; then
          git add .
          git commit -m "GitHub Actions: Update"
          git push origin HEAD:${GITHUB_REF}
        fi